services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_REDIRECT_URI=${VITE_GOOGLE_REDIRECT_URI}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_BACKEND_WS_URL=${VITE_BACKEND_WS_URL}
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
