version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - PROXY_SERVER_PORT=8000
      - WEBSOCKET_SERVER_PORT=8080
      - WEBSOCKET_SERVER_HOST=localhost
      - WEBSOCKET_SERVER_ENDPOINT=/requests # full path
      - PROXY_CERT_PATH=proxy.crt
      - PROXY_KEY_PATH=proxy.key