version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - PROXY_SERVER_PORT=8000
      - WEBSOCKET_SERVER_PORT=8080
