version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9000:8000
      - 9080:8080
    env_file:
      - .env
    # environment:
    #   - PROXY_SERVER_PORT=8000
    #   - WEBSOCKET_SERVER_PORT=8080
    #   - WEBSOCKET_SERVER_HOST=localhost
    #   - WEBSOCKET_SERVER_ENDPOINT=/requests # full path
    #   - PROXY_CERT_PATH=proxy.crt
    #   - PROXY_KEY_PATH=proxy.key
